CREATE TABLE GRUPO
(
    ID NUMBER NOT NULL,
    TITULO VARCHAR2(50),
    DESCRICAO VARCHAR2(250),
    CONSTRAINT ID_GRUPO_PK PRIMARY KEY (ID)
);

CREATE TABLE CONTATO
(   ID NUMBER NOT NULL,
    NOME VARCHAR2(100),
    CPF VARCHAR2(20),
    IDADE NUMBER,
    ENDERECO VARCHAR2(100),
    CONSTRAINT ID_CONTATO_PK PRIMARY KEY (ID)
);

CREATE TABLE GRUPOS
(
    ID NUMBER NOT NULL,
    ID_GRUPO NUMBER NOT NULL,
    ID_CONTATO NUMBER NOT NULL,
    CONSTRAINT ID_GRUPOS_PK PRIMARY KEY (ID),
    CONSTRAINT ID_GRUPOS_GRUPO_FK FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID) ON DELETE CASCADE,
    CONSTRAINT ID_GRUPOS_CONTATO_FK FOREIGN KEY (ID_CONTATO) REFERENCES CONTATO(ID) ON DELETE CASCADE
);

CREATE TABLE TELEFONE
(
    ID NUMBER NOT NULL,
    ID_CONTATO NUMBER NOT NULL,
    NUMERO VARCHAR2(50),
    CONSTRAINT ID_TELEFONE_PK PRIMARY KEY (ID),
    CONSTRAINT ID_CONTATO_TELEFONE_FK FOREIGN KEY (ID_CONTATO) REFERENCES CONTATO(ID) ON DELETE CASCADE
);

CREATE TABLE CAIXA
(
    ID NUMBER NOT NULL,
    ID_CONTATO NUMBER NOT NULL,
    VALOR NUMBER,
    DATA DATE,
    TITULO VARCHAR2(50),
    DESCRICAO VARCHAR2(250),
    CONSTRAINT ID_CAIXA_PK PRIMARY KEY (ID),
    CONSTRAINT ID_CONTATO_CAIXA_FK FOREIGN KEY (ID_CONTATO) REFERENCES CONTATO(ID) ON DELETE CASCADE
);
